@startuml diagrama_de_atividades

title Diagrama de Atividades - Reserva e Compra - SiGIE

|Cliente|
start
:Seleciona espetáculo, setor 
e número de lugares;
:Efetua pré-reserva no sistema;

|Sistema Informático|
:Verifica disponibilidade dos lugares;
if (Lugares disponíveis?) then (sim)
  :Regista pré-reserva e 
  gera número de reserva;
  :Calcula preço total, define data
  e hora limite para aquisição;
  :Exibe detalhes da pré-reserva;
else (não)
  :Exibe mensagem de 
  indisponibilidade;
  stop
endif

|Cliente|
:Verifica detalhes da pré-reserva;
:Dirige-se à bilheteira e
apresenta código de reserva;

|Funcionário|
:Recebe dados da reserva;
:Verifica a reserva no sistema;

|Sistema Informático|
:Consulta reserva e valida data-hora limite;

if (Reserva Válida?) then (Não)
    if (Bilhetes Disponíveis?) then (Não)
        |Funcionário|
        :Informa que não há 
        bilhetes disponíveis;

        |Cliente|
        :Informa que não há 
        bilhetes disponíveis;

        stop
    else (Sim)
    endif
else (Sim)
endif


|Funcionário|
:Efetua venda de bilhetes;

|Cliente|
:Efetua pagamento;

|Sistema Informático|
:Emite bilhete;

|Funcionário|
:Entrega bilhete ao cliente;

|Cliente|
:Recebe o bilhete;

stop

@enduml
