@startuml diagrama_de_sequencia

title Diagrama de Sequência - Reserva e Compra - SiGIE

actor Cliente
actor "Empregado de Caixa" as Empregado
participant "Sistema SiGIE" as Sistema


Cliente -> Empregado: Apresenta codigo de reserva
Empregado -> Sistema: Valida reserva
alt Reserva válida
    Sistema -> Cliente: Exibe preço final
    Cliente -> Empregado: Efetua pagamento
    Empregado -> Sistema: Regista pagamento
    Sistema -> Empregado: Emite bilhete
    Empregado -> Cliente: Entrega bilhete
else Reserva inválida
    Sistema -> Empregado: Informa que a reserva não é válida
    Empregado -> Sistema: Verifica se existem bilhetes disponíveis
    alt Existem bilhetes disponíveis
        Sistema -> Empregado: Informa que existem bilhetes disponíveis
        Empregado -> Cliente: Informa que existem bilhetes disponíveis
        Sistema -> Cliente: Exibe preço final
        Cliente -> Empregado: Efetua pagamento
        Empregado -> Sistema: Regista pagamento
        Sistema -> Empregado: Emite bilhete
        Empregado -> Cliente: Entrega bilhete
    else Não existem bilhetes disponíveis
        Sistema -> Empregado: Informa que não existem bilhetes disponíveis
        Empregado -> Cliente: Informa que não existem bilhetes disponíveis
    end
end

@enduml
