@startuml arquitetura_logica

title Arquitetura Lógica - SiGIE
left to right direction
skinparam componentStyle rectangle

package "Interface de Utilizador" {
  [App Móbil] as MobileApp
  [Website] as Website
}

package "Serviços de Negócio" {
  [Programação Cultural] as ProgramacaoCultural
  [Reserva e Venda de Bilhetes] as ReservaVendaBilhetes
  [Gestão de Clientes] as GestaoClientes
  [Estatísticas] as Estatisticas
  [Gestão de Instalações] as GestaoInstalacoes
  [Gestão de Artistas] as GestaoArtistas
}

package "Persistência de Dados" {
  [Base de Dados] as BD
}

' Conexões entre a Interface e os Serviços de Negócio
Website --> GestaoInstalacoes : "Gerir Salas, Sectores e Lugares"
Website --> ProgramacaoCultural : "Gerir Espectáculos\n(Programação e Reservas)"
Website --> GestaoClientes : "Registar Cliente"
Website --> ReservaVendaBilhetes : "Venda de Bilhetes"
Website --> Estatisticas : "Consultar Estatísticas"

MobileApp --> GestaoClientes : "Registar Cliente"
MobileApp --> ProgramacaoCultural : "Consultar Programação"
MobileApp --> ReservaVendaBilhetes : "Reservar Bilhetes"

' Conexões entre os Serviços de Negócio e a Base de Dados
GestaoInstalacoes --> BD
ProgramacaoCultural --> BD
GestaoArtistas --> BD
GestaoClientes --> BD
ReservaVendaBilhetes --> BD
Estatisticas --> BD

@enduml
