@startuml arquitetura_tecnologica

title Arquitetura Tecnológica - SiGIE

node "Cliente Web\n(Browser)" as WebClient
node "Cliente Mobile\n(App)" as MobileClient

node "Servidor Web/API" as WebServer {
  component "WebSite" as Frontend
  component "API" as API
}

node "Servidor de Aplicação" as AppServer {
  component "Lógica de Negócios\n(Reservas, Vendas, Gestão de Programação,\nRegisto de Salas, Artistas e Clientes)" as BusinessLogic
}

node "Servidor de Banco de Dados" as DBServer {
  database "Banco de Dados\n" as DB
}

' Fluxo de comunicação
WebClient --> WebServer
MobileClient --> WebServer
WebServer --> AppServer
AppServer --> DBServer

@enduml
